// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class git2 extends git2_1 {

    git2() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define PRIi32 "i"
     * }
     */
    public static MemorySegment PRIi32() {
        class Holder {
            static final MemorySegment PRIi32
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.PRIi32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIi64 "li"
     * }
     */
    public static MemorySegment PRIi64() {
        class Holder {
            static final MemorySegment PRIi64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIi64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiLEAST8 "i"
     * }
     */
    public static MemorySegment PRIiLEAST8() {
        class Holder {
            static final MemorySegment PRIiLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.PRIiLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiLEAST16 "i"
     * }
     */
    public static MemorySegment PRIiLEAST16() {
        class Holder {
            static final MemorySegment PRIiLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.PRIiLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiLEAST32 "i"
     * }
     */
    public static MemorySegment PRIiLEAST32() {
        class Holder {
            static final MemorySegment PRIiLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.PRIiLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiLEAST64 "li"
     * }
     */
    public static MemorySegment PRIiLEAST64() {
        class Holder {
            static final MemorySegment PRIiLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiFAST8 "i"
     * }
     */
    public static MemorySegment PRIiFAST8() {
        class Holder {
            static final MemorySegment PRIiFAST8
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.PRIiFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiFAST16 "li"
     * }
     */
    public static MemorySegment PRIiFAST16() {
        class Holder {
            static final MemorySegment PRIiFAST16
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiFAST32 "li"
     * }
     */
    public static MemorySegment PRIiFAST32() {
        class Holder {
            static final MemorySegment PRIiFAST32
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiFAST64 "li"
     * }
     */
    public static MemorySegment PRIiFAST64() {
        class Holder {
            static final MemorySegment PRIiFAST64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIo8 "o"
     * }
     */
    public static MemorySegment PRIo8() {
        class Holder {
            static final MemorySegment PRIo8
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIo8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIo16 "o"
     * }
     */
    public static MemorySegment PRIo16() {
        class Holder {
            static final MemorySegment PRIo16
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIo16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIo32 "o"
     * }
     */
    public static MemorySegment PRIo32() {
        class Holder {
            static final MemorySegment PRIo32
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIo32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIo64 "lo"
     * }
     */
    public static MemorySegment PRIo64() {
        class Holder {
            static final MemorySegment PRIo64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIo64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoLEAST8 "o"
     * }
     */
    public static MemorySegment PRIoLEAST8() {
        class Holder {
            static final MemorySegment PRIoLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIoLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoLEAST16 "o"
     * }
     */
    public static MemorySegment PRIoLEAST16() {
        class Holder {
            static final MemorySegment PRIoLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIoLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoLEAST32 "o"
     * }
     */
    public static MemorySegment PRIoLEAST32() {
        class Holder {
            static final MemorySegment PRIoLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIoLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoLEAST64 "lo"
     * }
     */
    public static MemorySegment PRIoLEAST64() {
        class Holder {
            static final MemorySegment PRIoLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoFAST8 "o"
     * }
     */
    public static MemorySegment PRIoFAST8() {
        class Holder {
            static final MemorySegment PRIoFAST8
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.PRIoFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoFAST16 "lo"
     * }
     */
    public static MemorySegment PRIoFAST16() {
        class Holder {
            static final MemorySegment PRIoFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoFAST32 "lo"
     * }
     */
    public static MemorySegment PRIoFAST32() {
        class Holder {
            static final MemorySegment PRIoFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoFAST64 "lo"
     * }
     */
    public static MemorySegment PRIoFAST64() {
        class Holder {
            static final MemorySegment PRIoFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIu8 "u"
     * }
     */
    public static MemorySegment PRIu8() {
        class Holder {
            static final MemorySegment PRIu8
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIu8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIu16 "u"
     * }
     */
    public static MemorySegment PRIu16() {
        class Holder {
            static final MemorySegment PRIu16
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIu16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIu32 "u"
     * }
     */
    public static MemorySegment PRIu32() {
        class Holder {
            static final MemorySegment PRIu32
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIu32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIu64 "lu"
     * }
     */
    public static MemorySegment PRIu64() {
        class Holder {
            static final MemorySegment PRIu64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIu64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuLEAST8 "u"
     * }
     */
    public static MemorySegment PRIuLEAST8() {
        class Holder {
            static final MemorySegment PRIuLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIuLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuLEAST16 "u"
     * }
     */
    public static MemorySegment PRIuLEAST16() {
        class Holder {
            static final MemorySegment PRIuLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIuLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuLEAST32 "u"
     * }
     */
    public static MemorySegment PRIuLEAST32() {
        class Holder {
            static final MemorySegment PRIuLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIuLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuLEAST64 "lu"
     * }
     */
    public static MemorySegment PRIuLEAST64() {
        class Holder {
            static final MemorySegment PRIuLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuFAST8 "u"
     * }
     */
    public static MemorySegment PRIuFAST8() {
        class Holder {
            static final MemorySegment PRIuFAST8
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.PRIuFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuFAST16 "lu"
     * }
     */
    public static MemorySegment PRIuFAST16() {
        class Holder {
            static final MemorySegment PRIuFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuFAST32 "lu"
     * }
     */
    public static MemorySegment PRIuFAST32() {
        class Holder {
            static final MemorySegment PRIuFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuFAST64 "lu"
     * }
     */
    public static MemorySegment PRIuFAST64() {
        class Holder {
            static final MemorySegment PRIuFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIx8 "x"
     * }
     */
    public static MemorySegment PRIx8() {
        class Holder {
            static final MemorySegment PRIx8
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIx8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIx16 "x"
     * }
     */
    public static MemorySegment PRIx16() {
        class Holder {
            static final MemorySegment PRIx16
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIx16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIx32 "x"
     * }
     */
    public static MemorySegment PRIx32() {
        class Holder {
            static final MemorySegment PRIx32
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIx32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIx64 "lx"
     * }
     */
    public static MemorySegment PRIx64() {
        class Holder {
            static final MemorySegment PRIx64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIx64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxLEAST8 "x"
     * }
     */
    public static MemorySegment PRIxLEAST8() {
        class Holder {
            static final MemorySegment PRIxLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIxLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxLEAST16 "x"
     * }
     */
    public static MemorySegment PRIxLEAST16() {
        class Holder {
            static final MemorySegment PRIxLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIxLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxLEAST32 "x"
     * }
     */
    public static MemorySegment PRIxLEAST32() {
        class Holder {
            static final MemorySegment PRIxLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIxLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxLEAST64 "lx"
     * }
     */
    public static MemorySegment PRIxLEAST64() {
        class Holder {
            static final MemorySegment PRIxLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxFAST8 "x"
     * }
     */
    public static MemorySegment PRIxFAST8() {
        class Holder {
            static final MemorySegment PRIxFAST8
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.PRIxFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxFAST16 "lx"
     * }
     */
    public static MemorySegment PRIxFAST16() {
        class Holder {
            static final MemorySegment PRIxFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxFAST32 "lx"
     * }
     */
    public static MemorySegment PRIxFAST32() {
        class Holder {
            static final MemorySegment PRIxFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxFAST64 "lx"
     * }
     */
    public static MemorySegment PRIxFAST64() {
        class Holder {
            static final MemorySegment PRIxFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIX8 "X"
     * }
     */
    public static MemorySegment PRIX8() {
        class Holder {
            static final MemorySegment PRIX8
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIX8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIX16 "X"
     * }
     */
    public static MemorySegment PRIX16() {
        class Holder {
            static final MemorySegment PRIX16
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIX16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIX32 "X"
     * }
     */
    public static MemorySegment PRIX32() {
        class Holder {
            static final MemorySegment PRIX32
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIX32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIX64 "lX"
     * }
     */
    public static MemorySegment PRIX64() {
        class Holder {
            static final MemorySegment PRIX64
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIX64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXLEAST8 "X"
     * }
     */
    public static MemorySegment PRIXLEAST8() {
        class Holder {
            static final MemorySegment PRIXLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIXLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXLEAST16 "X"
     * }
     */
    public static MemorySegment PRIXLEAST16() {
        class Holder {
            static final MemorySegment PRIXLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIXLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXLEAST32 "X"
     * }
     */
    public static MemorySegment PRIXLEAST32() {
        class Holder {
            static final MemorySegment PRIXLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIXLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXLEAST64 "lX"
     * }
     */
    public static MemorySegment PRIXLEAST64() {
        class Holder {
            static final MemorySegment PRIXLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXFAST8 "X"
     * }
     */
    public static MemorySegment PRIXFAST8() {
        class Holder {
            static final MemorySegment PRIXFAST8
                = git2.LIBRARY_ARENA.allocateFrom("X");
        }
        return Holder.PRIXFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXFAST16 "lX"
     * }
     */
    public static MemorySegment PRIXFAST16() {
        class Holder {
            static final MemorySegment PRIXFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXFAST32 "lX"
     * }
     */
    public static MemorySegment PRIXFAST32() {
        class Holder {
            static final MemorySegment PRIXFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXFAST64 "lX"
     * }
     */
    public static MemorySegment PRIXFAST64() {
        class Holder {
            static final MemorySegment PRIXFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define PRIdMAX "ld"
     * }
     */
    public static MemorySegment PRIdMAX() {
        class Holder {
            static final MemorySegment PRIdMAX
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.PRIdMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiMAX "li"
     * }
     */
    public static MemorySegment PRIiMAX() {
        class Holder {
            static final MemorySegment PRIiMAX
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoMAX "lo"
     * }
     */
    public static MemorySegment PRIoMAX() {
        class Holder {
            static final MemorySegment PRIoMAX
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuMAX "lu"
     * }
     */
    public static MemorySegment PRIuMAX() {
        class Holder {
            static final MemorySegment PRIuMAX
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxMAX "lx"
     * }
     */
    public static MemorySegment PRIxMAX() {
        class Holder {
            static final MemorySegment PRIxMAX
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXMAX "lX"
     * }
     */
    public static MemorySegment PRIXMAX() {
        class Holder {
            static final MemorySegment PRIXMAX
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXMAX;
    }
    /**
     * {@snippet lang=c :
     * #define PRIdPTR "ld"
     * }
     */
    public static MemorySegment PRIdPTR() {
        class Holder {
            static final MemorySegment PRIdPTR
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.PRIdPTR;
    }
    /**
     * {@snippet lang=c :
     * #define PRIiPTR "li"
     * }
     */
    public static MemorySegment PRIiPTR() {
        class Holder {
            static final MemorySegment PRIiPTR
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.PRIiPTR;
    }
    /**
     * {@snippet lang=c :
     * #define PRIoPTR "lo"
     * }
     */
    public static MemorySegment PRIoPTR() {
        class Holder {
            static final MemorySegment PRIoPTR
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.PRIoPTR;
    }
    /**
     * {@snippet lang=c :
     * #define PRIuPTR "lu"
     * }
     */
    public static MemorySegment PRIuPTR() {
        class Holder {
            static final MemorySegment PRIuPTR
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.PRIuPTR;
    }
    /**
     * {@snippet lang=c :
     * #define PRIxPTR "lx"
     * }
     */
    public static MemorySegment PRIxPTR() {
        class Holder {
            static final MemorySegment PRIxPTR
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.PRIxPTR;
    }
    /**
     * {@snippet lang=c :
     * #define PRIXPTR "lX"
     * }
     */
    public static MemorySegment PRIXPTR() {
        class Holder {
            static final MemorySegment PRIXPTR
                = git2.LIBRARY_ARENA.allocateFrom("lX");
        }
        return Holder.PRIXPTR;
    }
    /**
     * {@snippet lang=c :
     * #define SCNd8 "hhd"
     * }
     */
    public static MemorySegment SCNd8() {
        class Holder {
            static final MemorySegment SCNd8
                = git2.LIBRARY_ARENA.allocateFrom("hhd");
        }
        return Holder.SCNd8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNd16 "hd"
     * }
     */
    public static MemorySegment SCNd16() {
        class Holder {
            static final MemorySegment SCNd16
                = git2.LIBRARY_ARENA.allocateFrom("hd");
        }
        return Holder.SCNd16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNd32 "d"
     * }
     */
    public static MemorySegment SCNd32() {
        class Holder {
            static final MemorySegment SCNd32
                = git2.LIBRARY_ARENA.allocateFrom("d");
        }
        return Holder.SCNd32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNd64 "ld"
     * }
     */
    public static MemorySegment SCNd64() {
        class Holder {
            static final MemorySegment SCNd64
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNd64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdLEAST8 "hhd"
     * }
     */
    public static MemorySegment SCNdLEAST8() {
        class Holder {
            static final MemorySegment SCNdLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhd");
        }
        return Holder.SCNdLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdLEAST16 "hd"
     * }
     */
    public static MemorySegment SCNdLEAST16() {
        class Holder {
            static final MemorySegment SCNdLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("hd");
        }
        return Holder.SCNdLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdLEAST32 "d"
     * }
     */
    public static MemorySegment SCNdLEAST32() {
        class Holder {
            static final MemorySegment SCNdLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("d");
        }
        return Holder.SCNdLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdLEAST64 "ld"
     * }
     */
    public static MemorySegment SCNdLEAST64() {
        class Holder {
            static final MemorySegment SCNdLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdFAST8 "hhd"
     * }
     */
    public static MemorySegment SCNdFAST8() {
        class Holder {
            static final MemorySegment SCNdFAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhd");
        }
        return Holder.SCNdFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdFAST16 "ld"
     * }
     */
    public static MemorySegment SCNdFAST16() {
        class Holder {
            static final MemorySegment SCNdFAST16
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdFAST32 "ld"
     * }
     */
    public static MemorySegment SCNdFAST32() {
        class Holder {
            static final MemorySegment SCNdFAST32
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdFAST64 "ld"
     * }
     */
    public static MemorySegment SCNdFAST64() {
        class Holder {
            static final MemorySegment SCNdFAST64
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNi8 "hhi"
     * }
     */
    public static MemorySegment SCNi8() {
        class Holder {
            static final MemorySegment SCNi8
                = git2.LIBRARY_ARENA.allocateFrom("hhi");
        }
        return Holder.SCNi8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNi16 "hi"
     * }
     */
    public static MemorySegment SCNi16() {
        class Holder {
            static final MemorySegment SCNi16
                = git2.LIBRARY_ARENA.allocateFrom("hi");
        }
        return Holder.SCNi16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNi32 "i"
     * }
     */
    public static MemorySegment SCNi32() {
        class Holder {
            static final MemorySegment SCNi32
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.SCNi32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNi64 "li"
     * }
     */
    public static MemorySegment SCNi64() {
        class Holder {
            static final MemorySegment SCNi64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNi64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiLEAST8 "hhi"
     * }
     */
    public static MemorySegment SCNiLEAST8() {
        class Holder {
            static final MemorySegment SCNiLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhi");
        }
        return Holder.SCNiLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiLEAST16 "hi"
     * }
     */
    public static MemorySegment SCNiLEAST16() {
        class Holder {
            static final MemorySegment SCNiLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("hi");
        }
        return Holder.SCNiLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiLEAST32 "i"
     * }
     */
    public static MemorySegment SCNiLEAST32() {
        class Holder {
            static final MemorySegment SCNiLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("i");
        }
        return Holder.SCNiLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiLEAST64 "li"
     * }
     */
    public static MemorySegment SCNiLEAST64() {
        class Holder {
            static final MemorySegment SCNiLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiFAST8 "hhi"
     * }
     */
    public static MemorySegment SCNiFAST8() {
        class Holder {
            static final MemorySegment SCNiFAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhi");
        }
        return Holder.SCNiFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiFAST16 "li"
     * }
     */
    public static MemorySegment SCNiFAST16() {
        class Holder {
            static final MemorySegment SCNiFAST16
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiFAST32 "li"
     * }
     */
    public static MemorySegment SCNiFAST32() {
        class Holder {
            static final MemorySegment SCNiFAST32
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiFAST64 "li"
     * }
     */
    public static MemorySegment SCNiFAST64() {
        class Holder {
            static final MemorySegment SCNiFAST64
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNu8 "hhu"
     * }
     */
    public static MemorySegment SCNu8() {
        class Holder {
            static final MemorySegment SCNu8
                = git2.LIBRARY_ARENA.allocateFrom("hhu");
        }
        return Holder.SCNu8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNu16 "hu"
     * }
     */
    public static MemorySegment SCNu16() {
        class Holder {
            static final MemorySegment SCNu16
                = git2.LIBRARY_ARENA.allocateFrom("hu");
        }
        return Holder.SCNu16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNu32 "u"
     * }
     */
    public static MemorySegment SCNu32() {
        class Holder {
            static final MemorySegment SCNu32
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.SCNu32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNu64 "lu"
     * }
     */
    public static MemorySegment SCNu64() {
        class Holder {
            static final MemorySegment SCNu64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNu64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuLEAST8 "hhu"
     * }
     */
    public static MemorySegment SCNuLEAST8() {
        class Holder {
            static final MemorySegment SCNuLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhu");
        }
        return Holder.SCNuLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuLEAST16 "hu"
     * }
     */
    public static MemorySegment SCNuLEAST16() {
        class Holder {
            static final MemorySegment SCNuLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("hu");
        }
        return Holder.SCNuLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuLEAST32 "u"
     * }
     */
    public static MemorySegment SCNuLEAST32() {
        class Holder {
            static final MemorySegment SCNuLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("u");
        }
        return Holder.SCNuLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuLEAST64 "lu"
     * }
     */
    public static MemorySegment SCNuLEAST64() {
        class Holder {
            static final MemorySegment SCNuLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuFAST8 "hhu"
     * }
     */
    public static MemorySegment SCNuFAST8() {
        class Holder {
            static final MemorySegment SCNuFAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhu");
        }
        return Holder.SCNuFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuFAST16 "lu"
     * }
     */
    public static MemorySegment SCNuFAST16() {
        class Holder {
            static final MemorySegment SCNuFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuFAST32 "lu"
     * }
     */
    public static MemorySegment SCNuFAST32() {
        class Holder {
            static final MemorySegment SCNuFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuFAST64 "lu"
     * }
     */
    public static MemorySegment SCNuFAST64() {
        class Holder {
            static final MemorySegment SCNuFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNo8 "hho"
     * }
     */
    public static MemorySegment SCNo8() {
        class Holder {
            static final MemorySegment SCNo8
                = git2.LIBRARY_ARENA.allocateFrom("hho");
        }
        return Holder.SCNo8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNo16 "ho"
     * }
     */
    public static MemorySegment SCNo16() {
        class Holder {
            static final MemorySegment SCNo16
                = git2.LIBRARY_ARENA.allocateFrom("ho");
        }
        return Holder.SCNo16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNo32 "o"
     * }
     */
    public static MemorySegment SCNo32() {
        class Holder {
            static final MemorySegment SCNo32
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.SCNo32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNo64 "lo"
     * }
     */
    public static MemorySegment SCNo64() {
        class Holder {
            static final MemorySegment SCNo64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNo64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoLEAST8 "hho"
     * }
     */
    public static MemorySegment SCNoLEAST8() {
        class Holder {
            static final MemorySegment SCNoLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("hho");
        }
        return Holder.SCNoLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoLEAST16 "ho"
     * }
     */
    public static MemorySegment SCNoLEAST16() {
        class Holder {
            static final MemorySegment SCNoLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("ho");
        }
        return Holder.SCNoLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoLEAST32 "o"
     * }
     */
    public static MemorySegment SCNoLEAST32() {
        class Holder {
            static final MemorySegment SCNoLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("o");
        }
        return Holder.SCNoLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoLEAST64 "lo"
     * }
     */
    public static MemorySegment SCNoLEAST64() {
        class Holder {
            static final MemorySegment SCNoLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoFAST8 "hho"
     * }
     */
    public static MemorySegment SCNoFAST8() {
        class Holder {
            static final MemorySegment SCNoFAST8
                = git2.LIBRARY_ARENA.allocateFrom("hho");
        }
        return Holder.SCNoFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoFAST16 "lo"
     * }
     */
    public static MemorySegment SCNoFAST16() {
        class Holder {
            static final MemorySegment SCNoFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoFAST32 "lo"
     * }
     */
    public static MemorySegment SCNoFAST32() {
        class Holder {
            static final MemorySegment SCNoFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoFAST64 "lo"
     * }
     */
    public static MemorySegment SCNoFAST64() {
        class Holder {
            static final MemorySegment SCNoFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNx8 "hhx"
     * }
     */
    public static MemorySegment SCNx8() {
        class Holder {
            static final MemorySegment SCNx8
                = git2.LIBRARY_ARENA.allocateFrom("hhx");
        }
        return Holder.SCNx8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNx16 "hx"
     * }
     */
    public static MemorySegment SCNx16() {
        class Holder {
            static final MemorySegment SCNx16
                = git2.LIBRARY_ARENA.allocateFrom("hx");
        }
        return Holder.SCNx16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNx32 "x"
     * }
     */
    public static MemorySegment SCNx32() {
        class Holder {
            static final MemorySegment SCNx32
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.SCNx32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNx64 "lx"
     * }
     */
    public static MemorySegment SCNx64() {
        class Holder {
            static final MemorySegment SCNx64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNx64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxLEAST8 "hhx"
     * }
     */
    public static MemorySegment SCNxLEAST8() {
        class Holder {
            static final MemorySegment SCNxLEAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhx");
        }
        return Holder.SCNxLEAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxLEAST16 "hx"
     * }
     */
    public static MemorySegment SCNxLEAST16() {
        class Holder {
            static final MemorySegment SCNxLEAST16
                = git2.LIBRARY_ARENA.allocateFrom("hx");
        }
        return Holder.SCNxLEAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxLEAST32 "x"
     * }
     */
    public static MemorySegment SCNxLEAST32() {
        class Holder {
            static final MemorySegment SCNxLEAST32
                = git2.LIBRARY_ARENA.allocateFrom("x");
        }
        return Holder.SCNxLEAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxLEAST64 "lx"
     * }
     */
    public static MemorySegment SCNxLEAST64() {
        class Holder {
            static final MemorySegment SCNxLEAST64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxLEAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxFAST8 "hhx"
     * }
     */
    public static MemorySegment SCNxFAST8() {
        class Holder {
            static final MemorySegment SCNxFAST8
                = git2.LIBRARY_ARENA.allocateFrom("hhx");
        }
        return Holder.SCNxFAST8;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxFAST16 "lx"
     * }
     */
    public static MemorySegment SCNxFAST16() {
        class Holder {
            static final MemorySegment SCNxFAST16
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxFAST16;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxFAST32 "lx"
     * }
     */
    public static MemorySegment SCNxFAST32() {
        class Holder {
            static final MemorySegment SCNxFAST32
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxFAST32;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxFAST64 "lx"
     * }
     */
    public static MemorySegment SCNxFAST64() {
        class Holder {
            static final MemorySegment SCNxFAST64
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxFAST64;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdMAX "ld"
     * }
     */
    public static MemorySegment SCNdMAX() {
        class Holder {
            static final MemorySegment SCNdMAX
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdMAX;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiMAX "li"
     * }
     */
    public static MemorySegment SCNiMAX() {
        class Holder {
            static final MemorySegment SCNiMAX
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiMAX;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoMAX "lo"
     * }
     */
    public static MemorySegment SCNoMAX() {
        class Holder {
            static final MemorySegment SCNoMAX
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoMAX;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuMAX "lu"
     * }
     */
    public static MemorySegment SCNuMAX() {
        class Holder {
            static final MemorySegment SCNuMAX
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuMAX;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxMAX "lx"
     * }
     */
    public static MemorySegment SCNxMAX() {
        class Holder {
            static final MemorySegment SCNxMAX
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxMAX;
    }
    /**
     * {@snippet lang=c :
     * #define SCNdPTR "ld"
     * }
     */
    public static MemorySegment SCNdPTR() {
        class Holder {
            static final MemorySegment SCNdPTR
                = git2.LIBRARY_ARENA.allocateFrom("ld");
        }
        return Holder.SCNdPTR;
    }
    /**
     * {@snippet lang=c :
     * #define SCNiPTR "li"
     * }
     */
    public static MemorySegment SCNiPTR() {
        class Holder {
            static final MemorySegment SCNiPTR
                = git2.LIBRARY_ARENA.allocateFrom("li");
        }
        return Holder.SCNiPTR;
    }
    /**
     * {@snippet lang=c :
     * #define SCNoPTR "lo"
     * }
     */
    public static MemorySegment SCNoPTR() {
        class Holder {
            static final MemorySegment SCNoPTR
                = git2.LIBRARY_ARENA.allocateFrom("lo");
        }
        return Holder.SCNoPTR;
    }
    /**
     * {@snippet lang=c :
     * #define SCNuPTR "lu"
     * }
     */
    public static MemorySegment SCNuPTR() {
        class Holder {
            static final MemorySegment SCNuPTR
                = git2.LIBRARY_ARENA.allocateFrom("lu");
        }
        return Holder.SCNuPTR;
    }
    /**
     * {@snippet lang=c :
     * #define SCNxPTR "lx"
     * }
     */
    public static MemorySegment SCNxPTR() {
        class Holder {
            static final MemorySegment SCNxPTR
                = git2.LIBRARY_ARENA.allocateFrom("lx");
        }
        return Holder.SCNxPTR;
    }
    private static final int GIT_PATH_LIST_SEPARATOR = (int)58L;
    /**
     * {@snippet lang=c :
     * #define GIT_PATH_LIST_SEPARATOR 58
     * }
     */
    public static int GIT_PATH_LIST_SEPARATOR() {
        return GIT_PATH_LIST_SEPARATOR;
    }
    private static final int GIT_OID_DEFAULT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_DEFAULT 1
     * }
     */
    public static int GIT_OID_DEFAULT() {
        return GIT_OID_DEFAULT;
    }
    private static final int GIT_OID_SHA1_HEXSIZE = (int)40L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_SHA1_HEXSIZE 40
     * }
     */
    public static int GIT_OID_SHA1_HEXSIZE() {
        return GIT_OID_SHA1_HEXSIZE;
    }
    /**
     * {@snippet lang=c :
     * #define GIT_OID_SHA1_HEXZERO "0000000000000000000000000000000000000000"
     * }
     */
    public static MemorySegment GIT_OID_SHA1_HEXZERO() {
        class Holder {
            static final MemorySegment GIT_OID_SHA1_HEXZERO
                = git2.LIBRARY_ARENA.allocateFrom("0000000000000000000000000000000000000000");
        }
        return Holder.GIT_OID_SHA1_HEXZERO;
    }
    private static final int GIT_OID_MAX_SIZE = (int)20L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_MAX_SIZE 20
     * }
     */
    public static int GIT_OID_MAX_SIZE() {
        return GIT_OID_MAX_SIZE;
    }
    private static final int GIT_OID_MAX_HEXSIZE = (int)40L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_MAX_HEXSIZE 40
     * }
     */
    public static int GIT_OID_MAX_HEXSIZE() {
        return GIT_OID_MAX_HEXSIZE;
    }
    private static final long GIT_OBJECT_SIZE_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJECT_SIZE_MAX -1
     * }
     */
    public static long GIT_OBJECT_SIZE_MAX() {
        return GIT_OBJECT_SIZE_MAX;
    }
    private static final int GIT_ATTR_CHECK_NO_SYSTEM = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_CHECK_NO_SYSTEM 4
     * }
     */
    public static int GIT_ATTR_CHECK_NO_SYSTEM() {
        return GIT_ATTR_CHECK_NO_SYSTEM;
    }
    private static final int GIT_ATTR_CHECK_INCLUDE_HEAD = (int)8L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_CHECK_INCLUDE_HEAD 8
     * }
     */
    public static int GIT_ATTR_CHECK_INCLUDE_HEAD() {
        return GIT_ATTR_CHECK_INCLUDE_HEAD;
    }
    private static final int GIT_ATTR_CHECK_INCLUDE_COMMIT = (int)16L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_CHECK_INCLUDE_COMMIT 16
     * }
     */
    public static int GIT_ATTR_CHECK_INCLUDE_COMMIT() {
        return GIT_ATTR_CHECK_INCLUDE_COMMIT;
    }
    private static final int GIT_INDEX_ENTRY_NAMEMASK = (int)4095L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEX_ENTRY_NAMEMASK 4095
     * }
     */
    public static int GIT_INDEX_ENTRY_NAMEMASK() {
        return GIT_INDEX_ENTRY_NAMEMASK;
    }
    private static final int GIT_INDEX_ENTRY_STAGEMASK = (int)12288L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEX_ENTRY_STAGEMASK 12288
     * }
     */
    public static int GIT_INDEX_ENTRY_STAGEMASK() {
        return GIT_INDEX_ENTRY_STAGEMASK;
    }
    /**
     * {@snippet lang=c :
     * #define GIT_DEFAULT_PORT "9418"
     * }
     */
    public static MemorySegment GIT_DEFAULT_PORT() {
        class Holder {
            static final MemorySegment GIT_DEFAULT_PORT
                = git2.LIBRARY_ARENA.allocateFrom("9418");
        }
        return Holder.GIT_DEFAULT_PORT;
    }
    private static final long GIT_REBASE_NO_OPERATION = -1L;
    /**
     * {@snippet lang=c :
     * #define GIT_REBASE_NO_OPERATION -1
     * }
     */
    public static long GIT_REBASE_NO_OPERATION() {
        return GIT_REBASE_NO_OPERATION;
    }
    private static final int GIT_STATUS_OPT_DEFAULTS = (int)19L;
    /**
     * {@snippet lang=c :
     * #define GIT_STATUS_OPT_DEFAULTS 19
     * }
     */
    public static int GIT_STATUS_OPT_DEFAULTS() {
        return GIT_STATUS_OPT_DEFAULTS;
    }
    private static final int GIT_SUBMODULE_STATUS__IN_FLAGS = (int)15L;
    /**
     * {@snippet lang=c :
     * #define GIT_SUBMODULE_STATUS__IN_FLAGS 15
     * }
     */
    public static int GIT_SUBMODULE_STATUS__IN_FLAGS() {
        return GIT_SUBMODULE_STATUS__IN_FLAGS;
    }
    private static final int GIT_SUBMODULE_STATUS__INDEX_FLAGS = (int)112L;
    /**
     * {@snippet lang=c :
     * #define GIT_SUBMODULE_STATUS__INDEX_FLAGS 112
     * }
     */
    public static int GIT_SUBMODULE_STATUS__INDEX_FLAGS() {
        return GIT_SUBMODULE_STATUS__INDEX_FLAGS;
    }
    private static final int GIT_SUBMODULE_STATUS__WD_FLAGS = (int)16256L;
    /**
     * {@snippet lang=c :
     * #define GIT_SUBMODULE_STATUS__WD_FLAGS 16256
     * }
     */
    public static int GIT_SUBMODULE_STATUS__WD_FLAGS() {
        return GIT_SUBMODULE_STATUS__WD_FLAGS;
    }
    private static final int GIT_ATTR_UNSPECIFIED_T = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_UNSPECIFIED_T 0
     * }
     */
    public static int GIT_ATTR_UNSPECIFIED_T() {
        return GIT_ATTR_UNSPECIFIED_T;
    }
    private static final int GIT_ATTR_TRUE_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_TRUE_T 1
     * }
     */
    public static int GIT_ATTR_TRUE_T() {
        return GIT_ATTR_TRUE_T;
    }
    private static final int GIT_ATTR_FALSE_T = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_FALSE_T 2
     * }
     */
    public static int GIT_ATTR_FALSE_T() {
        return GIT_ATTR_FALSE_T;
    }
    private static final int GIT_ATTR_VALUE_T = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GIT_ATTR_VALUE_T 3
     * }
     */
    public static int GIT_ATTR_VALUE_T() {
        return GIT_ATTR_VALUE_T;
    }
    private static final int GIT_BLOB_FILTER_ATTTRIBUTES_FROM_HEAD = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_BLOB_FILTER_ATTTRIBUTES_FROM_HEAD 4
     * }
     */
    public static int GIT_BLOB_FILTER_ATTTRIBUTES_FROM_HEAD() {
        return GIT_BLOB_FILTER_ATTTRIBUTES_FROM_HEAD;
    }
    private static final int GIT_CVAR_FALSE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GIT_CVAR_FALSE 0
     * }
     */
    public static int GIT_CVAR_FALSE() {
        return GIT_CVAR_FALSE;
    }
    private static final int GIT_CVAR_TRUE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_CVAR_TRUE 1
     * }
     */
    public static int GIT_CVAR_TRUE() {
        return GIT_CVAR_TRUE;
    }
    private static final int GIT_CVAR_INT32 = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_CVAR_INT32 2
     * }
     */
    public static int GIT_CVAR_INT32() {
        return GIT_CVAR_INT32;
    }
    private static final int GIT_CVAR_STRING = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GIT_CVAR_STRING 3
     * }
     */
    public static int GIT_CVAR_STRING() {
        return GIT_CVAR_STRING;
    }
    private static final int GITERR_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GITERR_NONE 0
     * }
     */
    public static int GITERR_NONE() {
        return GITERR_NONE;
    }
    private static final int GITERR_NOMEMORY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GITERR_NOMEMORY 1
     * }
     */
    public static int GITERR_NOMEMORY() {
        return GITERR_NOMEMORY;
    }
    private static final int GITERR_OS = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GITERR_OS 2
     * }
     */
    public static int GITERR_OS() {
        return GITERR_OS;
    }
    private static final int GITERR_INVALID = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GITERR_INVALID 3
     * }
     */
    public static int GITERR_INVALID() {
        return GITERR_INVALID;
    }
    private static final int GITERR_REFERENCE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GITERR_REFERENCE 4
     * }
     */
    public static int GITERR_REFERENCE() {
        return GITERR_REFERENCE;
    }
    private static final int GITERR_ZLIB = (int)5L;
    /**
     * {@snippet lang=c :
     * #define GITERR_ZLIB 5
     * }
     */
    public static int GITERR_ZLIB() {
        return GITERR_ZLIB;
    }
    private static final int GITERR_REPOSITORY = (int)6L;
    /**
     * {@snippet lang=c :
     * #define GITERR_REPOSITORY 6
     * }
     */
    public static int GITERR_REPOSITORY() {
        return GITERR_REPOSITORY;
    }
    private static final int GITERR_CONFIG = (int)7L;
    /**
     * {@snippet lang=c :
     * #define GITERR_CONFIG 7
     * }
     */
    public static int GITERR_CONFIG() {
        return GITERR_CONFIG;
    }
    private static final int GITERR_REGEX = (int)8L;
    /**
     * {@snippet lang=c :
     * #define GITERR_REGEX 8
     * }
     */
    public static int GITERR_REGEX() {
        return GITERR_REGEX;
    }
    private static final int GITERR_ODB = (int)9L;
    /**
     * {@snippet lang=c :
     * #define GITERR_ODB 9
     * }
     */
    public static int GITERR_ODB() {
        return GITERR_ODB;
    }
    private static final int GITERR_INDEX = (int)10L;
    /**
     * {@snippet lang=c :
     * #define GITERR_INDEX 10
     * }
     */
    public static int GITERR_INDEX() {
        return GITERR_INDEX;
    }
    private static final int GITERR_OBJECT = (int)11L;
    /**
     * {@snippet lang=c :
     * #define GITERR_OBJECT 11
     * }
     */
    public static int GITERR_OBJECT() {
        return GITERR_OBJECT;
    }
    private static final int GITERR_NET = (int)12L;
    /**
     * {@snippet lang=c :
     * #define GITERR_NET 12
     * }
     */
    public static int GITERR_NET() {
        return GITERR_NET;
    }
    private static final int GITERR_TAG = (int)13L;
    /**
     * {@snippet lang=c :
     * #define GITERR_TAG 13
     * }
     */
    public static int GITERR_TAG() {
        return GITERR_TAG;
    }
    private static final int GITERR_TREE = (int)14L;
    /**
     * {@snippet lang=c :
     * #define GITERR_TREE 14
     * }
     */
    public static int GITERR_TREE() {
        return GITERR_TREE;
    }
    private static final int GITERR_INDEXER = (int)15L;
    /**
     * {@snippet lang=c :
     * #define GITERR_INDEXER 15
     * }
     */
    public static int GITERR_INDEXER() {
        return GITERR_INDEXER;
    }
    private static final int GITERR_SSL = (int)16L;
    /**
     * {@snippet lang=c :
     * #define GITERR_SSL 16
     * }
     */
    public static int GITERR_SSL() {
        return GITERR_SSL;
    }
    private static final int GITERR_SUBMODULE = (int)17L;
    /**
     * {@snippet lang=c :
     * #define GITERR_SUBMODULE 17
     * }
     */
    public static int GITERR_SUBMODULE() {
        return GITERR_SUBMODULE;
    }
    private static final int GITERR_THREAD = (int)18L;
    /**
     * {@snippet lang=c :
     * #define GITERR_THREAD 18
     * }
     */
    public static int GITERR_THREAD() {
        return GITERR_THREAD;
    }
    private static final int GITERR_STASH = (int)19L;
    /**
     * {@snippet lang=c :
     * #define GITERR_STASH 19
     * }
     */
    public static int GITERR_STASH() {
        return GITERR_STASH;
    }
    private static final int GITERR_CHECKOUT = (int)20L;
    /**
     * {@snippet lang=c :
     * #define GITERR_CHECKOUT 20
     * }
     */
    public static int GITERR_CHECKOUT() {
        return GITERR_CHECKOUT;
    }
    private static final int GITERR_FETCHHEAD = (int)21L;
    /**
     * {@snippet lang=c :
     * #define GITERR_FETCHHEAD 21
     * }
     */
    public static int GITERR_FETCHHEAD() {
        return GITERR_FETCHHEAD;
    }
    private static final int GITERR_MERGE = (int)22L;
    /**
     * {@snippet lang=c :
     * #define GITERR_MERGE 22
     * }
     */
    public static int GITERR_MERGE() {
        return GITERR_MERGE;
    }
    private static final int GITERR_SSH = (int)23L;
    /**
     * {@snippet lang=c :
     * #define GITERR_SSH 23
     * }
     */
    public static int GITERR_SSH() {
        return GITERR_SSH;
    }
    private static final int GITERR_FILTER = (int)24L;
    /**
     * {@snippet lang=c :
     * #define GITERR_FILTER 24
     * }
     */
    public static int GITERR_FILTER() {
        return GITERR_FILTER;
    }
    private static final int GITERR_REVERT = (int)25L;
    /**
     * {@snippet lang=c :
     * #define GITERR_REVERT 25
     * }
     */
    public static int GITERR_REVERT() {
        return GITERR_REVERT;
    }
    private static final int GITERR_CALLBACK = (int)26L;
    /**
     * {@snippet lang=c :
     * #define GITERR_CALLBACK 26
     * }
     */
    public static int GITERR_CALLBACK() {
        return GITERR_CALLBACK;
    }
    private static final int GITERR_CHERRYPICK = (int)27L;
    /**
     * {@snippet lang=c :
     * #define GITERR_CHERRYPICK 27
     * }
     */
    public static int GITERR_CHERRYPICK() {
        return GITERR_CHERRYPICK;
    }
    private static final int GITERR_DESCRIBE = (int)28L;
    /**
     * {@snippet lang=c :
     * #define GITERR_DESCRIBE 28
     * }
     */
    public static int GITERR_DESCRIBE() {
        return GITERR_DESCRIBE;
    }
    private static final int GITERR_REBASE = (int)29L;
    /**
     * {@snippet lang=c :
     * #define GITERR_REBASE 29
     * }
     */
    public static int GITERR_REBASE() {
        return GITERR_REBASE;
    }
    private static final int GITERR_FILESYSTEM = (int)30L;
    /**
     * {@snippet lang=c :
     * #define GITERR_FILESYSTEM 30
     * }
     */
    public static int GITERR_FILESYSTEM() {
        return GITERR_FILESYSTEM;
    }
    private static final int GITERR_PATCH = (int)31L;
    /**
     * {@snippet lang=c :
     * #define GITERR_PATCH 31
     * }
     */
    public static int GITERR_PATCH() {
        return GITERR_PATCH;
    }
    private static final int GITERR_WORKTREE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define GITERR_WORKTREE 32
     * }
     */
    public static int GITERR_WORKTREE() {
        return GITERR_WORKTREE;
    }
    private static final int GITERR_SHA1 = (int)33L;
    /**
     * {@snippet lang=c :
     * #define GITERR_SHA1 33
     * }
     */
    public static int GITERR_SHA1() {
        return GITERR_SHA1;
    }
    private static final int GIT_ERROR_SHA1 = (int)33L;
    /**
     * {@snippet lang=c :
     * #define GIT_ERROR_SHA1 33
     * }
     */
    public static int GIT_ERROR_SHA1() {
        return GIT_ERROR_SHA1;
    }
    private static final int GIT_IDXENTRY_NAMEMASK = (int)4095L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_NAMEMASK 4095
     * }
     */
    public static int GIT_IDXENTRY_NAMEMASK() {
        return GIT_IDXENTRY_NAMEMASK;
    }
    private static final int GIT_IDXENTRY_STAGEMASK = (int)12288L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_STAGEMASK 12288
     * }
     */
    public static int GIT_IDXENTRY_STAGEMASK() {
        return GIT_IDXENTRY_STAGEMASK;
    }
    private static final int GIT_IDXENTRY_STAGESHIFT = (int)12L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_STAGESHIFT 12
     * }
     */
    public static int GIT_IDXENTRY_STAGESHIFT() {
        return GIT_IDXENTRY_STAGESHIFT;
    }
    private static final int GIT_IDXENTRY_EXTENDED = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_EXTENDED 16384
     * }
     */
    public static int GIT_IDXENTRY_EXTENDED() {
        return GIT_IDXENTRY_EXTENDED;
    }
    private static final int GIT_IDXENTRY_VALID = (int)32768L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_VALID 32768
     * }
     */
    public static int GIT_IDXENTRY_VALID() {
        return GIT_IDXENTRY_VALID;
    }
    private static final int GIT_IDXENTRY_INTENT_TO_ADD = (int)8192L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_INTENT_TO_ADD 8192
     * }
     */
    public static int GIT_IDXENTRY_INTENT_TO_ADD() {
        return GIT_IDXENTRY_INTENT_TO_ADD;
    }
    private static final int GIT_IDXENTRY_SKIP_WORKTREE = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_SKIP_WORKTREE 16384
     * }
     */
    public static int GIT_IDXENTRY_SKIP_WORKTREE() {
        return GIT_IDXENTRY_SKIP_WORKTREE;
    }
    private static final int GIT_IDXENTRY_EXTENDED_FLAGS = (int)24576L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_EXTENDED_FLAGS 24576
     * }
     */
    public static int GIT_IDXENTRY_EXTENDED_FLAGS() {
        return GIT_IDXENTRY_EXTENDED_FLAGS;
    }
    private static final int GIT_IDXENTRY_EXTENDED2 = (int)32768L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_EXTENDED2 32768
     * }
     */
    public static int GIT_IDXENTRY_EXTENDED2() {
        return GIT_IDXENTRY_EXTENDED2;
    }
    private static final int GIT_IDXENTRY_UPDATE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_UPDATE 1
     * }
     */
    public static int GIT_IDXENTRY_UPDATE() {
        return GIT_IDXENTRY_UPDATE;
    }
    private static final int GIT_IDXENTRY_REMOVE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_REMOVE 2
     * }
     */
    public static int GIT_IDXENTRY_REMOVE() {
        return GIT_IDXENTRY_REMOVE;
    }
    private static final int GIT_IDXENTRY_UPTODATE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_UPTODATE 4
     * }
     */
    public static int GIT_IDXENTRY_UPTODATE() {
        return GIT_IDXENTRY_UPTODATE;
    }
    private static final int GIT_IDXENTRY_ADDED = (int)8L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_ADDED 8
     * }
     */
    public static int GIT_IDXENTRY_ADDED() {
        return GIT_IDXENTRY_ADDED;
    }
    private static final int GIT_IDXENTRY_HASHED = (int)16L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_HASHED 16
     * }
     */
    public static int GIT_IDXENTRY_HASHED() {
        return GIT_IDXENTRY_HASHED;
    }
    private static final int GIT_IDXENTRY_UNHASHED = (int)32L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_UNHASHED 32
     * }
     */
    public static int GIT_IDXENTRY_UNHASHED() {
        return GIT_IDXENTRY_UNHASHED;
    }
    private static final int GIT_IDXENTRY_WT_REMOVE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_WT_REMOVE 64
     * }
     */
    public static int GIT_IDXENTRY_WT_REMOVE() {
        return GIT_IDXENTRY_WT_REMOVE;
    }
    private static final int GIT_IDXENTRY_CONFLICTED = (int)128L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_CONFLICTED 128
     * }
     */
    public static int GIT_IDXENTRY_CONFLICTED() {
        return GIT_IDXENTRY_CONFLICTED;
    }
    private static final int GIT_IDXENTRY_UNPACKED = (int)256L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_UNPACKED 256
     * }
     */
    public static int GIT_IDXENTRY_UNPACKED() {
        return GIT_IDXENTRY_UNPACKED;
    }
    private static final int GIT_IDXENTRY_NEW_SKIP_WORKTREE = (int)512L;
    /**
     * {@snippet lang=c :
     * #define GIT_IDXENTRY_NEW_SKIP_WORKTREE 512
     * }
     */
    public static int GIT_IDXENTRY_NEW_SKIP_WORKTREE() {
        return GIT_IDXENTRY_NEW_SKIP_WORKTREE;
    }
    private static final int GIT_INDEXCAP_IGNORE_CASE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEXCAP_IGNORE_CASE 1
     * }
     */
    public static int GIT_INDEXCAP_IGNORE_CASE() {
        return GIT_INDEXCAP_IGNORE_CASE;
    }
    private static final int GIT_INDEXCAP_NO_FILEMODE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEXCAP_NO_FILEMODE 2
     * }
     */
    public static int GIT_INDEXCAP_NO_FILEMODE() {
        return GIT_INDEXCAP_NO_FILEMODE;
    }
    private static final int GIT_INDEXCAP_NO_SYMLINKS = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEXCAP_NO_SYMLINKS 4
     * }
     */
    public static int GIT_INDEXCAP_NO_SYMLINKS() {
        return GIT_INDEXCAP_NO_SYMLINKS;
    }
    private static final int GIT_INDEXCAP_FROM_OWNER = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GIT_INDEXCAP_FROM_OWNER -1
     * }
     */
    public static int GIT_INDEXCAP_FROM_OWNER() {
        return GIT_INDEXCAP_FROM_OWNER;
    }
    private static final int GIT_OBJ_ANY = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_ANY -2
     * }
     */
    public static int GIT_OBJ_ANY() {
        return GIT_OBJ_ANY;
    }
    private static final int GIT_OBJ_BAD = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_BAD -1
     * }
     */
    public static int GIT_OBJ_BAD() {
        return GIT_OBJ_BAD;
    }
    private static final int GIT_OBJ_COMMIT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_COMMIT 1
     * }
     */
    public static int GIT_OBJ_COMMIT() {
        return GIT_OBJ_COMMIT;
    }
    private static final int GIT_OBJ_TREE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_TREE 2
     * }
     */
    public static int GIT_OBJ_TREE() {
        return GIT_OBJ_TREE;
    }
    private static final int GIT_OBJ_BLOB = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_BLOB 3
     * }
     */
    public static int GIT_OBJ_BLOB() {
        return GIT_OBJ_BLOB;
    }
    private static final int GIT_OBJ_TAG = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_TAG 4
     * }
     */
    public static int GIT_OBJ_TAG() {
        return GIT_OBJ_TAG;
    }
    private static final int GIT_OBJ_OFS_DELTA = (int)6L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_OFS_DELTA 6
     * }
     */
    public static int GIT_OBJ_OFS_DELTA() {
        return GIT_OBJ_OFS_DELTA;
    }
    private static final int GIT_OBJ_REF_DELTA = (int)7L;
    /**
     * {@snippet lang=c :
     * #define GIT_OBJ_REF_DELTA 7
     * }
     */
    public static int GIT_OBJ_REF_DELTA() {
        return GIT_OBJ_REF_DELTA;
    }
    private static final int GIT_REF_INVALID = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_INVALID 0
     * }
     */
    public static int GIT_REF_INVALID() {
        return GIT_REF_INVALID;
    }
    private static final int GIT_REF_OID = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_OID 1
     * }
     */
    public static int GIT_REF_OID() {
        return GIT_REF_OID;
    }
    private static final int GIT_REF_SYMBOLIC = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_SYMBOLIC 2
     * }
     */
    public static int GIT_REF_SYMBOLIC() {
        return GIT_REF_SYMBOLIC;
    }
    private static final int GIT_REF_LISTALL = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_LISTALL 3
     * }
     */
    public static int GIT_REF_LISTALL() {
        return GIT_REF_LISTALL;
    }
    private static final int GIT_REF_FORMAT_NORMAL = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_FORMAT_NORMAL 0
     * }
     */
    public static int GIT_REF_FORMAT_NORMAL() {
        return GIT_REF_FORMAT_NORMAL;
    }
    private static final int GIT_REF_FORMAT_ALLOW_ONELEVEL = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_FORMAT_ALLOW_ONELEVEL 1
     * }
     */
    public static int GIT_REF_FORMAT_ALLOW_ONELEVEL() {
        return GIT_REF_FORMAT_ALLOW_ONELEVEL;
    }
    private static final int GIT_REF_FORMAT_REFSPEC_PATTERN = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_FORMAT_REFSPEC_PATTERN 2
     * }
     */
    public static int GIT_REF_FORMAT_REFSPEC_PATTERN() {
        return GIT_REF_FORMAT_REFSPEC_PATTERN;
    }
    private static final int GIT_REF_FORMAT_REFSPEC_SHORTHAND = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_REF_FORMAT_REFSPEC_SHORTHAND 4
     * }
     */
    public static int GIT_REF_FORMAT_REFSPEC_SHORTHAND() {
        return GIT_REF_FORMAT_REFSPEC_SHORTHAND;
    }
    private static final int GIT_REVPARSE_SINGLE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_REVPARSE_SINGLE 1
     * }
     */
    public static int GIT_REVPARSE_SINGLE() {
        return GIT_REVPARSE_SINGLE;
    }
    private static final int GIT_REVPARSE_RANGE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_REVPARSE_RANGE 2
     * }
     */
    public static int GIT_REVPARSE_RANGE() {
        return GIT_REVPARSE_RANGE;
    }
    private static final int GIT_REVPARSE_MERGE_BASE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_REVPARSE_MERGE_BASE 4
     * }
     */
    public static int GIT_REVPARSE_MERGE_BASE() {
        return GIT_REVPARSE_MERGE_BASE;
    }
    private static final int GIT_CREDTYPE_USERPASS_PLAINTEXT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_USERPASS_PLAINTEXT 1
     * }
     */
    public static int GIT_CREDTYPE_USERPASS_PLAINTEXT() {
        return GIT_CREDTYPE_USERPASS_PLAINTEXT;
    }
    private static final int GIT_CREDTYPE_SSH_KEY = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_SSH_KEY 2
     * }
     */
    public static int GIT_CREDTYPE_SSH_KEY() {
        return GIT_CREDTYPE_SSH_KEY;
    }
    private static final int GIT_CREDTYPE_SSH_CUSTOM = (int)4L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_SSH_CUSTOM 4
     * }
     */
    public static int GIT_CREDTYPE_SSH_CUSTOM() {
        return GIT_CREDTYPE_SSH_CUSTOM;
    }
    private static final int GIT_CREDTYPE_DEFAULT = (int)8L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_DEFAULT 8
     * }
     */
    public static int GIT_CREDTYPE_DEFAULT() {
        return GIT_CREDTYPE_DEFAULT;
    }
    private static final int GIT_CREDTYPE_SSH_INTERACTIVE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_SSH_INTERACTIVE 16
     * }
     */
    public static int GIT_CREDTYPE_SSH_INTERACTIVE() {
        return GIT_CREDTYPE_SSH_INTERACTIVE;
    }
    private static final int GIT_CREDTYPE_USERNAME = (int)32L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_USERNAME 32
     * }
     */
    public static int GIT_CREDTYPE_USERNAME() {
        return GIT_CREDTYPE_USERNAME;
    }
    private static final int GIT_CREDTYPE_SSH_MEMORY = (int)64L;
    /**
     * {@snippet lang=c :
     * #define GIT_CREDTYPE_SSH_MEMORY 64
     * }
     */
    public static int GIT_CREDTYPE_SSH_MEMORY() {
        return GIT_CREDTYPE_SSH_MEMORY;
    }
    private static final int GIT_OID_RAWSZ = (int)20L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_RAWSZ 20
     * }
     */
    public static int GIT_OID_RAWSZ() {
        return GIT_OID_RAWSZ;
    }
    private static final int GIT_OID_HEXSZ = (int)40L;
    /**
     * {@snippet lang=c :
     * #define GIT_OID_HEXSZ 40
     * }
     */
    public static int GIT_OID_HEXSZ() {
        return GIT_OID_HEXSZ;
    }
    /**
     * {@snippet lang=c :
     * #define GIT_OID_HEX_ZERO "0000000000000000000000000000000000000000"
     * }
     */
    public static MemorySegment GIT_OID_HEX_ZERO() {
        class Holder {
            static final MemorySegment GIT_OID_HEX_ZERO
                = git2.LIBRARY_ARENA.allocateFrom("0000000000000000000000000000000000000000");
        }
        return Holder.GIT_OID_HEX_ZERO;
    }
    private static final int LIBGIT2_VER_MAJOR = (int)1L;
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VER_MAJOR 1
     * }
     */
    public static int LIBGIT2_VER_MAJOR() {
        return LIBGIT2_VER_MAJOR;
    }
    private static final int LIBGIT2_VER_MINOR = (int)9L;
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VER_MINOR 9
     * }
     */
    public static int LIBGIT2_VER_MINOR() {
        return LIBGIT2_VER_MINOR;
    }
    private static final int LIBGIT2_VER_REVISION = (int)0L;
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VER_REVISION 0
     * }
     */
    public static int LIBGIT2_VER_REVISION() {
        return LIBGIT2_VER_REVISION;
    }
    private static final int LIBGIT2_VER_PATCH = (int)0L;
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VER_PATCH 0
     * }
     */
    public static int LIBGIT2_VER_PATCH() {
        return LIBGIT2_VER_PATCH;
    }
    private static final MemorySegment LIBGIT2_VER_PRERELEASE = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VER_PRERELEASE (void*) 0
     * }
     */
    public static MemorySegment LIBGIT2_VER_PRERELEASE() {
        return LIBGIT2_VER_PRERELEASE;
    }
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VERSION "1.9.0"
     * }
     */
    public static MemorySegment LIBGIT2_VERSION() {
        class Holder {
            static final MemorySegment LIBGIT2_VERSION
                = git2.LIBRARY_ARENA.allocateFrom("1.9.0");
        }
        return Holder.LIBGIT2_VERSION;
    }
    private static final MemorySegment LIBGIT2_VERSION_PRERELEASE = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VERSION_PRERELEASE (void*) 0
     * }
     */
    public static MemorySegment LIBGIT2_VERSION_PRERELEASE() {
        return LIBGIT2_VERSION_PRERELEASE;
    }
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_SOVERSION "1.9"
     * }
     */
    public static MemorySegment LIBGIT2_SOVERSION() {
        class Holder {
            static final MemorySegment LIBGIT2_SOVERSION
                = git2.LIBRARY_ARENA.allocateFrom("1.9");
        }
        return Holder.LIBGIT2_SOVERSION;
    }
    private static final int LIBGIT2_VERSION_NUMBER = (int)1090000L;
    /**
     * {@snippet lang=c :
     * #define LIBGIT2_VERSION_NUMBER 1090000
     * }
     */
    public static int LIBGIT2_VERSION_NUMBER() {
        return LIBGIT2_VERSION_NUMBER;
    }
}

