// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct git_credential_ssh_interactive {
 *     git_credential parent;
 *     char *username;
 *     git_credential_ssh_interactive_cb prompt_callback;
 *     void *payload;
 * }
 * }
 */
public class git_credential_ssh_interactive {

    git_credential_ssh_interactive() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        git_credential.layout().withName("parent"),
        git2.C_POINTER.withName("username"),
        git2.C_POINTER.withName("prompt_callback"),
        git2.C_POINTER.withName("payload")
    ).withName("git_credential_ssh_interactive");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout parent$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("parent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * git_credential parent
     * }
     */
    public static final GroupLayout parent$layout() {
        return parent$LAYOUT;
    }

    private static final long parent$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * git_credential parent
     * }
     */
    public static final long parent$offset() {
        return parent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * git_credential parent
     * }
     */
    public static MemorySegment parent(MemorySegment struct) {
        return struct.asSlice(parent$OFFSET, parent$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * git_credential parent
     * }
     */
    public static void parent(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, parent$OFFSET, parent$LAYOUT.byteSize());
    }

    private static final AddressLayout username$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("username"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *username
     * }
     */
    public static final AddressLayout username$layout() {
        return username$LAYOUT;
    }

    private static final long username$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *username
     * }
     */
    public static final long username$offset() {
        return username$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *username
     * }
     */
    public static MemorySegment username(MemorySegment struct) {
        return struct.get(username$LAYOUT, username$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *username
     * }
     */
    public static void username(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(username$LAYOUT, username$OFFSET, fieldValue);
    }

    private static final AddressLayout prompt_callback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("prompt_callback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * git_credential_ssh_interactive_cb prompt_callback
     * }
     */
    public static final AddressLayout prompt_callback$layout() {
        return prompt_callback$LAYOUT;
    }

    private static final long prompt_callback$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * git_credential_ssh_interactive_cb prompt_callback
     * }
     */
    public static final long prompt_callback$offset() {
        return prompt_callback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * git_credential_ssh_interactive_cb prompt_callback
     * }
     */
    public static MemorySegment prompt_callback(MemorySegment struct) {
        return struct.get(prompt_callback$LAYOUT, prompt_callback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * git_credential_ssh_interactive_cb prompt_callback
     * }
     */
    public static void prompt_callback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(prompt_callback$LAYOUT, prompt_callback$OFFSET, fieldValue);
    }

    private static final AddressLayout payload$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("payload"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *payload
     * }
     */
    public static final AddressLayout payload$layout() {
        return payload$LAYOUT;
    }

    private static final long payload$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *payload
     * }
     */
    public static final long payload$offset() {
        return payload$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *payload
     * }
     */
    public static MemorySegment payload(MemorySegment struct) {
        return struct.get(payload$LAYOUT, payload$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *payload
     * }
     */
    public static void payload(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(payload$LAYOUT, payload$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

