// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef git_credential_ssh_interactive git_cred_ssh_interactive
 * }
 */
public class git_cred_ssh_interactive extends git_credential_ssh_interactive {

    git_cred_ssh_interactive() {
        // Should not be called directly
    }
}

