// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*git_diff_notify_cb)(const git_diff *, const git_diff_delta *, const char *, void *)
 * }
 */
public class git_diff_notify_cb {

    git_diff_notify_cb() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment diff_so_far, MemorySegment delta_to_add, MemorySegment matched_pathspec, MemorySegment payload);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        git2.C_INT,
        git2.C_POINTER,
        git2.C_POINTER,
        git2.C_POINTER,
        git2.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = git2.upcallHandle(git_diff_notify_cb.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(git_diff_notify_cb.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment diff_so_far, MemorySegment delta_to_add, MemorySegment matched_pathspec, MemorySegment payload) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, diff_so_far, delta_to_add, matched_pathspec, payload);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

