// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*git_credential_sign_cb)(LIBSSH2_SESSION *, unsigned char **, size_t *, const unsigned char *, size_t, void **)
 * }
 */
public class git_credential_sign_cb {

    git_credential_sign_cb() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment session, MemorySegment sig, MemorySegment sig_len, MemorySegment data, long data_len, MemorySegment abstract_);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        git2.C_INT,
        git2.C_POINTER,
        git2.C_POINTER,
        git2.C_POINTER,
        git2.C_POINTER,
        git2.C_LONG,
        git2.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = git2.upcallHandle(git_credential_sign_cb.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(git_credential_sign_cb.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment session, MemorySegment sig, MemorySegment sig_len, MemorySegment data, long data_len, MemorySegment abstract_) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, session, sig, sig_len, data, data_len, abstract_);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

