// Generated by jextract

package com.sernamar.jgit2.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct git_signature {
 *     char *name;
 *     char *email;
 *     git_time when;
 * }
 * }
 */
public class git_signature {

    git_signature() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        git2.C_POINTER.withName("name"),
        git2.C_POINTER.withName("email"),
        git_time.layout().withName("when")
    ).withName("git_signature");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout email$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("email"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *email
     * }
     */
    public static final AddressLayout email$layout() {
        return email$LAYOUT;
    }

    private static final long email$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *email
     * }
     */
    public static final long email$offset() {
        return email$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *email
     * }
     */
    public static MemorySegment email(MemorySegment struct) {
        return struct.get(email$LAYOUT, email$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *email
     * }
     */
    public static void email(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(email$LAYOUT, email$OFFSET, fieldValue);
    }

    private static final GroupLayout when$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("when"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * git_time when
     * }
     */
    public static final GroupLayout when$layout() {
        return when$LAYOUT;
    }

    private static final long when$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * git_time when
     * }
     */
    public static final long when$offset() {
        return when$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * git_time when
     * }
     */
    public static MemorySegment when(MemorySegment struct) {
        return struct.asSlice(when$OFFSET, when$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * git_time when
     * }
     */
    public static void when(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, when$OFFSET, when$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

